//! 构建期把 `content/` 内嵌进二进制 —— 段 2 的前置。
//!
//! **为什么必须内嵌**：`wasm32-unknown-unknown` 上没有文件系统，Worker 里读不到
//! `content/`。`crates/dev` 原先用 `std::fs` 在运行时读，那条路在线上不存在。
//!
//! **为什么是 build script 而不是 committed 的生成文件**：生成文件会引入一整类新的
//! 漂移（「改了 TOML 忘了重新生成」），然后还要再造一道门禁去防它。build script 配上
//! `cargo:rerun-if-changed` 结构上不可能过期 —— cargo 看见 content/ 变了就重跑。
//!
//! ⚠️ 这里的 I/O 发生在**构建期的构建脚本**里，脚本本身不进产物。
//! `crates/site` 的库代码仍然零 I/O，那条硬约束没有松动。
//!
//! 产物顺序必须与 `crates/dev` 原先的读取顺序**逐字节一致**：根目录 `*.toml`
//! 按文件名排序 → `generated/repo.json` → `tools/*.toml` 按文件名排序。
//! 条目顺序决定页面上的卡片顺序，`xtask render-diff` 会逐字节比对这一点。

use std::path::{Path, PathBuf};

fn main() {
    let content = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../content");
    let content = content
        .canonicalize()
        .unwrap_or_else(|e| panic!("找不到 content 目录 {}: {e}", content.display()));

    // 目录本身也要监听 —— 只监听已知文件的话，**新增**一个条目不会触发重编，
    // 那正是「站点少了一条而构建是绿的」这类静默事故。
    println!("cargo:rerun-if-changed={}", content.display());
    println!("cargo:rerun-if-changed={}", content.join("tools").display());
    println!(
        "cargo:rerun-if-changed={}",
        content.join("generated").display()
    );

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for p in sorted_files(&content, "toml") {
        entries.push((rel(&p), p));
    }
    let repo_json = content.join("generated/repo.json");
    if repo_json.is_file() {
        entries.push((rel(&repo_json), repo_json));
    }
    for p in sorted_files(&content.join("tools"), "toml") {
        entries.push((rel(&p), p));
    }

    let mut out = String::from(
        "// @generated by crates/site/build.rs —— 不要手改，改 content/ 下的 TOML。\n\
         /// 全部内容源，`(仓库相对路径, 原文)`。路径只用于报错信息。\n\
         pub const SOURCES: &[(&str, &str)] = &[\n",
    );
    for (rel_path, abs) in &entries {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel_path,
            abs.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR 未设置")).join("content.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("写 {} 失败: {e}", dest.display()));
}

fn sorted_files(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = match std::fs::read_dir(dir) {
        Ok(rd) => rd
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some(ext))
            .collect(),
        Err(e) => panic!("无法读取 {}: {e}", dir.display()),
    };
    // 按文件名排序（不是整条路径）—— 与 crates/dev 原先的 sort_by_key(file_name) 对齐。
    out.sort_by_key(|p| p.file_name().map(|s| s.to_owned()));
    out
}

/// 绝对路径 → `content/...` 仓库相对路径，用于报错信息里的可点位置。
fn rel(p: &Path) -> String {
    let s = p.to_string_lossy();
    match s.find("/content/") {
        Some(i) => s[i + 1..].to_string(),
        None => s.to_string(),
    }
}
